### ISSUE TITLE
not enough arguments in call to gonduit.NewClient

### ISSUE THREAD

**Issue by evaldasou** [shuLhan/j2p#1]
Hi,
Any idea what's missing here?:

go get -u github.com/shuLhan/j2p
src/github.com/shuLhan/j2p/j2p.go:73: not enough arguments in call to gonduit.NewClient

**Comment by shuLhan** [comment]
It was missing option to skip TLS check on Phabricator. Latest commit fix this issue [1].

Try `go get -u` again and set option `secure` in `phabricator` config either true or false (depends on your server).

Thank you for reporting this issue.

[1] https://github.com/shuLhan/j2p/commit/f32ea1c2c2afd9e8f3cddb4ee8c15087a357d59c
